# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/mapper/luks-0bbf6be0-db3e-42ae-80c7-728a4a4b15b3";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-0bbf6be0-db3e-42ae-80c7-728a4a4b15b3".device = "/dev/disk/by-uuid/0bbf6be0-db3e-42ae-80c7-728a4a4b15b3";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/E892-1667";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [
    {device = "/dev/mapper/luks-d02a6bb1-c177-4755-aa67-8346658d878f";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
