# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt extendedglob
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/simen/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# PATH
export PATH=$PATH:/home/simen/.local/bin

# zinit
ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"
[ ! -d $ZINIT_HOME ] && mkdir -p "$(dirname $ZINIT_HOME)"
[ ! -d $ZINIT_HOME/.git ] && git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
source "${ZINIT_HOME}/zinit.zsh"

eval "$(ssh-agent -s)" &>/dev/null

# zinit plugins
zinit light zsh-users/zsh-syntax-highlighting
zinit light zsh-users/zsh-completions
zinit light zsh-users/zsh-autosuggestions

export FZF_CTRL_T_COMMAND=""
source <(fzf --zsh)
export FZF_DEFAULT_OPTS="--style=full \
--height=40% \
--reverse \
--color 'pointer:green:bold,bg+:-1:,fg+:green:bold,info:blue:bold,marker:yellow:bold,hl:gray:bold,hl+:yellow:bold' \
--input-label ' Search ' \
--color 'input-border:blue,input-label:blue:bold' \
--list-label ' Results ' \
--color 'list-border:green,list-label:green:bold' \
--preview-label ' Preview ' \
--color 'preview-border:magenta,preview-label:magenta:bold'"

export FZF_COMPLETION_TRIGGER='*'
eval "$(direnv hook zsh)"

eval "$(oh-my-posh init zsh --config ~/.config/ohmyposh/themes/everforest.omp.json)"

eval "$(zoxide init zsh)"
alias cd="z"

# Keybinds
bindkey '^[[1;5C' forward-word
bindkey '^[[1;5D' backward-word
bindkey '^H' backward-kill-word
bindkey '^f' autosuggest-accept
WORDCHARS='*?._-[]~=&;!#$%^(){}<>'

# Styling
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"

# Aliases
alias ls="ls --color"
alias nano="echo 'use vim brah 🙏🥀'"

if [[ "$OSTYPE" == "darwin"* ]]; then
  alias onedrive="cd /Users/simen/Library/CloudStorage/OneDrive-Osloskolen/VG1/IM/IT/"
fi

alias update="sudo xbps-install -u xbps && sudo xbps-install -Suy && flatpak update -y && echo 'FULL UPDATE SCRIPT DONE'"
export PATH="/usr/local/opt/postgresql@18/bin:$PATH"
