{
  pkgs,
  lib,
  config,
  osConfig,
  inputs,
  ...
}: let
  isNixOS = lib.hasAttr "nixos" osConfig.system;
  flakePath =
    if isNixOS
    then "/etc/nixos"
    else if pkgs.stdenv.isDarwin
    then "/Users/simen/nix"
    else "/home/simen/.config/nix-config";

  hostName = osConfig.networking.hostName;

  # Shared config: same content across all machines (auto-generated by DMS from settings)
  sharedPath = "${flakePath}/config/shared";
  # Per-host config: monitor layouts, widget positions, plugin runtime state
  hostPath = "${flakePath}/config/hosts/${hostName}";

  mkLink = config.lib.file.mkOutOfStoreSymlink;
in {
  imports = [
    inputs.dankMaterialShell.homeModules.dank-material-shell
    #inputs.dankMaterialShell.homeModules.dankMaterialShell.niri
  ];

  options = {
    dms = {
      enable = lib.mkEnableOption "Enable dank-niri module";
    };
  };

  config = lib.mkIf config.dms.enable {
    programs.dank-material-shell = {
      enable = true;

      systemd = {
        enable = true;
        restartIfChanged = true;
      };

      enableSystemMonitoring = true;
      enableVPN = true;
      enableDynamicTheming = true;
      enableAudioWavelength = true;
      enableCalendarEvents = true;

      plugins = {
        dankBatteryAlerts.src = inputs.dms-plugins + "/DankBatteryAlerts";
        dankPomodoroTimer.src = inputs.dms-plugins + "/DankPomodoroTimer";
        dms-display-mirror.src = inputs.dms-display-mirror;
        NetbirdStatus.src = inputs.dms-plugins-dadangdut33 + "/NetbirdStatus";
      };
    };

    home.file = {
      # ── Base niri config ──────────────────────────────────────────────────
      ".config/niri/config.kdl".source = mkLink "${sharedPath}/niri/config.kdl";

      # ── Shared DMS niri configs ───────────────────────────────────────────
      ".config/niri/dms/alttab.kdl".source = mkLink "${sharedPath}/niri/dms/alttab.kdl";
      ".config/niri/dms/binds.kdl".source = mkLink "${sharedPath}/niri/dms/binds.kdl";
      ".config/niri/dms/colors.kdl".source = mkLink "${sharedPath}/niri/dms/colors.kdl";
      ".config/niri/dms/input.kdl".source = mkLink "${sharedPath}/niri/dms/input.kdl";
      ".config/niri/dms/layout.kdl".source = mkLink "${sharedPath}/niri/dms/layout.kdl";
      ".config/niri/dms/windowrules.kdl".source = mkLink "${sharedPath}/niri/dms/windowrules.kdl";
      ".config/niri/dms/wpblur.kdl".source = mkLink "${sharedPath}/niri/dms/wpblur.kdl";

      # ── Firefox userChrome CSS ────────────────────────────────────────────
      ".config/DankMaterialShell/firefox.css".source = mkLink "${sharedPath}/DankMaterialShell/firefox.css";

      # ── Per-host niri config ──────────────────────────────────────────────
      ".config/niri/dms/outputs.kdl".source = mkLink "${hostPath}/niri/dms/outputs.kdl";
      ".config/niri/dms/cursor.kdl".source = mkLink "${hostPath}/niri/dms/cursor.kdl";

      # ── Per-host DMS settings ─────────────────────────────────────────────
      ".config/DankMaterialShell/settings.json".source =
        mkLink "${hostPath}/DankMaterialShell/settings.json";
      ".config/DankMaterialShell/plugin_settings.json".source =
        mkLink "${hostPath}/DankMaterialShell/plugin_settings.json";
    };

    home.packages = with pkgs; [
      kdePackages.breeze-icons
    ];
  };
}
